Refactor restore_db utility

diff --git a/bin/restore_db b/bin/restore_db
--- a/bin/restore_db
+++ b/bin/restore_db
@@ -1,3 +1,21 @@
 #!/bin/bash
+die () {
+    echo >&2 "$@"
+    exit 1
+}
 
-tar -xOf $2 | gunzip | psql $3 
+[ "$#" -eq 3 ] || die "3 arguments required, $# provided - <type of db> <backup file> <database to restore>"
+
+case $1 in
+pg)
+  echo "Restoring postgres backup to database $3..."
+  tar -xOf $2 | gunzip | psql $3 > /dev/null
+  ;;
+mysql)
+  echo "Restoring mysql backup to database $3..."
+  tar -xOf $2 | gunzip | mysql $3
+  ;;
+*)
+  echo "Usage: <type of db> <backup file> <database to restore>"
+  ;;
+esac
